### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by deadcombo** [Helium314/SCEE#424]
**How to Reproduce**
Launch the app.

**Expected Behavior**
Successfully launch.

**Does it happen in normal StreetComplete?**
No. I can use it completely.

**Versions affected**
52.1

````
type: crash
osVersion: google/cheetah/cheetah:13/TQ2A.230305.008.C1/2023040400:user/release-keys
package: de.westnordost.streetcomplete.expert:5202
process: de.westnordost.streetcomplete.expert
processUptime: 504 + 321 ms

org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.edithistory.EditHistoryController']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
	at org.koin.core.scope.Scope.get(Scope.kt:205)
	at de.westnordost.streetcomplete.StreetCompleteApplication$special$$inlined$inject$default$6.invoke(ComponentCallbackExt.kt:131)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.westnordost.streetcomplete.StreetCompleteApplication.getEditHistoryController(StreetCompleteApplication.kt:77)
	at de.westnordost.streetcomplete.StreetCompleteApplication.access$getEditHistoryController(StreetCompleteApplication.kt:70)
	at de.westnordost.streetcomplete.StreetCompleteApplication$onCreate$2.invokeSuspend(StreetCompleteApplication.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Application), StandaloneCoroutine{Cancelling}@7ddca77, Dispatchers.Default]
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.osm.edits.ElementEditsController']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
	at org.koin.core.scope.Scope.get(Scope.kt:205)
	at de.westnordost.streetcomplete.data.edithistory.EditHistoryModuleKt$editHistoryModule$1$2.invoke(EditHistoryModule.kt:131)
	at de.westnordost.streetcomplete.data.edithistory.EditHistoryModuleKt$editHistoryModule$1$2.invoke(EditHistoryModule.kt:7)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 20 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'de.westnordost.streetcomplete.data.osm.edits.ElementEditsDao']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
	at org.koin.core.scope.Scope.get(Scope.kt:205)
	at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$10.invoke(ElementEditsModule.kt:131)
	at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$10.invoke(ElementEditsModule.kt:27)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 32 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.Database']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
	at org.koin.core.scope.Scope.get(Scope.kt:205)
	at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$3.invoke(ElementEditsModule.kt:131)
	at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$3.invoke(ElementEditsModule.kt:17)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 40 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'io.requery.android.database.sqlite.SQLiteOpenHelper']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
	at org.koin.core.scope.Scope.get(Scope.kt:205)
	at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$1.invoke(DbModule.kt:131)
	at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$1.invoke(DbModule.kt:8)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 52 more
Caused by: java.lang.IllegalStateException: getDatabase called recursively
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:215)
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:174)
	at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.onCreate(StreetCompleteSQLiteOpenHelper.kt:102)
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:268)
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:174)
	at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.<init>(StreetCompleteSQLiteOpenHelper.kt:113)
	at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$2.invoke(DbModule.kt:9)
	at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$2.invoke(DbModule.kt:9)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 64 more

````

**Comment by Helium314** [comment]
This is really bad... 52.1 was supposed to fix a few crashes, not to create more.
Worst thing is that I can simply reproduce the issue by clearing data.

Did you have an older version installed before, or is 52.1 the first version you installed?
To me it looks like installing 52.0, start it once, and then upgrade to 52.1 works.

**Comment by HolgerJeromin** [comment]
I had a new phone.
Installed 52.1 and got a crash on start.
Deinstall
Install 52.0, worked
Updated to 52.1, worked too.

**Comment by Helium314** [comment]
Thanks!
The crash is fixed, but I'll leave the issue open until the next release

**Comment by deadcombo** [comment]
New install, however I will follow that workaround now.

**Comment by Helium314** [comment]
Next version will come soon, so I'll close this.
