### ISSUE TITLE
Crash on piste:lit (?) quest

### ISSUE THREAD

**Issue by HolgerJeromin** [Helium314/SCEE#502]
Describe how to reproduce it here:

Selected and answered piste:lit quest
Probably
https://www.openstreetmap.org/way/932888370#map=15/47.8558/7.9534

````

                Thread: unknown
        App version: 55.11
        Device: motorola  devonf, Android 13
        Locale: de_DE
        Stack trace:
java.lang.IllegalArgumentException: positions is empty
	at de.westnordost.streetcomplete.util.math.SphericalEarthMathKt.enclosingBoundingBox(SphericalEarthMath.kt:235)
	at de.westnordost.streetcomplete.data.osm.mapdata.MapDataController.updateAll(MapDataController.kt:144)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(ElementEditsUploader.kt:90)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.access$uploadEdit(ElementEditsUploader.kt:40)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invokeSuspend(ElementEditsUploader.kt:72)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invoke(ElementEditsUploader.kt:0)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invoke(ElementEditsUploader.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1.invokeSuspend(ElementEditsUploader.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


        Last log before crash:
        2023-12-27 19:41:39.983 I MapDataController: Fetched 3029 elements and geometries in 13ms
2023-12-27 19:41:42.803 I MainFragment: onPause
2023-12-27 19:41:43.555 I MainFragment: onStop (remove listeners)
2023-12-27 19:41:43.555 I MainFragment: onSaveInstanceState
2023-12-27 19:43:35.297 I MainFragment: onStart (add listeners)
2023-12-27 19:43:35.325 I MapDataController: Fetched 3029 elements and geometries in 3ms
2023-12-27 19:43:35.334 I MainFragment: onResume
2023-12-27 19:43:35.341 I QuestAutoSyncer: Checking whether to automatically download new quests at 47.8531938,7.9479489
2023-12-27 19:43:35.347 I MapDataController: Fetched 2069 elements and geometries in 4ms
2023-12-27 19:43:35.348 I QuestAutoSyncer: All downloaded in radius of 552 meters around user (16 tiles)
2023-12-27 19:43:35.405 I Upload: Starting upload
2023-12-27 19:43:35.412 I Upload: Finished upload
2023-12-27 19:43:36.689 I MapDataController: Fetched 3417 elements and geometries in 4ms
2023-12-27 19:43:36.788 I MapDataController: Fetched 3984 elements and geometries in 5ms
2023-12-27 19:43:37.706 I MapDataController: Fetched 1997 elements and geometries in 1ms
2023-12-27 19:43:39.501 I MapDataController: Fetched 4208 elements and geometries in 4ms
2023-12-27 19:43:39.652 I MapDataController: Fetched 2180 elements and geometries in 5ms
2023-12-27 19:43:41.664 I MainFragment: showElementDetails for WAY 94234066
2023-12-27 19:43:42.857 I MainFragment: closeBottomSheet while showing WAY 94234066
2023-12-27 19:43:46.436 I MainFragment: showQuestDetails for OsmQuestKey(elementType=WAY, elementId=932888368, questTypeName=AddPisteLit)
2023-12-27 19:43:55.239 I QuestAutoSyncer: Checking whether to automatically download new quests at 47.8532550,7.9478933
2023-12-27 19:43:55.244 I MapDataController: Fetched 2069 elements and geometries in 3ms
2023-12-27 19:43:55.246 I QuestAutoSyncer: All downloaded in radius of 552 meters around user (16 tiles)
2023-12-27 19:43:55.872 I AbstractOsmQuestForm: solve AddPisteLit for WAY 932888368, extra: false, in TagEditor: false
2023-12-27 19:43:55.879 I EditHistoryController: history: add edit AddPisteLit for [WAY 932888368]
2023-12-27 19:43:55.880 I MapDataWithEditsSource: updated: [WAY 932888368], deleted: []
2023-12-27 19:43:55.896 I OsmQuestController: Created 0 quests for 1 updated elements in 0.0s
2023-12-27 19:43:55.897 I VisibleQuestsSource: added [], deleted: [OsmQuestKey(elementType=WAY, elementId=932888368, questTypeName=AddPisteLit)]
2023-12-27 19:43:55.898 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=WAY, elementId=932888368, questTypeName=AddPisteLit)
2023-12-27 19:43:55.900 I OsmQuestController: Persisted 0 new and removed 1 already resolved quests in 0.0s
2023-12-27 19:43:55.905 I MainFragment: edited: AddPisteLit
2023-12-27 19:43:55.913 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:43:55.916 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:43:55.919 I Upload: Starting upload
2023-12-27 19:43:56.666 I ChangesetManager: Created changeset #145588426
2023-12-27 19:43:57.164 D ElementEditsUploader: Uploaded a UpdateElementTagsAction for [WAY 932888368]
2023-12-27 19:43:57.191 I Upload: Finished upload
2023-12-27 19:43:58.223 I MainFragment: showQuestDetails for OsmQuestKey(elementType=WAY, elementId=549011475, questTypeName=AddPisteLit)
2023-12-27 19:43:59.401 I MapDataCache: need to fetch data in [TilesRect(left=136856, top=91292, right=136863, bottom=91295)] from database
2023-12-27 19:43:59.430 I MapDataController: Fetched 1430 elements and geometries in 30ms
2023-12-27 19:44:01.958 I AbstractOsmQuestForm: solve AddPisteLit for WAY 549011475, extra: false, in TagEditor: false
2023-12-27 19:44:01.963 I EditHistoryController: history: add edit AddPisteLit for [WAY 549011475]
2023-12-27 19:44:01.964 I MapDataWithEditsSource: updated: [WAY 549011475], deleted: []
2023-12-27 19:44:01.980 I OsmQuestController: Created 0 quests for 1 updated elements in 0.0s
2023-12-27 19:44:01.980 I VisibleQuestsSource: added [], deleted: [OsmQuestKey(elementType=WAY, elementId=549011475, questTypeName=AddPisteLit)]
2023-12-27 19:44:01.981 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=WAY, elementId=549011475, questTypeName=AddPisteLit)
2023-12-27 19:44:01.984 I OsmQuestController: Persisted 0 new and removed 1 already resolved quests in 0.0s
2023-12-27 19:44:01.987 I MainFragment: edited: AddPisteLit
2023-12-27 19:44:01.994 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:44:02.003 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:44:02.013 I Upload: Starting upload
2023-12-27 19:44:02.434 D ElementEditsUploader: Uploaded a UpdateElementTagsAction for [WAY 549011475]
2023-12-27 19:44:02.513 I Upload: Finished upload
2023-12-27 19:44:04.337 I MainFragment: showQuestDetails for OsmQuestKey(elementType=WAY, elementId=549011476, questTypeName=AddPisteLit)
2023-12-27 19:44:05.486 I AbstractOsmQuestForm: solve AddPisteLit for WAY 549011476, extra: false, in TagEditor: false
2023-12-27 19:44:05.490 I EditHistoryController: history: add edit AddPisteLit for [WAY 549011476]
2023-12-27 19:44:05.491 I MapDataWithEditsSource: updated: [WAY 549011476], deleted: []
2023-12-27 19:44:05.502 I OsmQuestController: Created 0 quests for 1 updated elements in 0.0s
2023-12-27 19:44:05.502 I VisibleQuestsSource: added [], deleted: [OsmQuestKey(elementType=WAY, elementId=549011476, questTypeName=AddPisteLit)]
2023-12-27 19:44:05.502 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=WAY, elementId=549011476, questTypeName=AddPisteLit)
2023-12-27 19:44:05.505 I OsmQuestController: Persisted 0 new and removed 1 already resolved quests in 0.0s
2023-12-27 19:44:05.511 I MainFragment: edited: AddPisteLit
2023-12-27 19:44:05.518 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:44:05.519 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:44:05.523 I Upload: Starting upload
2023-12-27 19:44:05.712 D ElementEditsUploader: Uploaded a UpdateElementTagsAction for [WAY 549011476]
2023-12-27 19:44:05.757 I Upload: Finished upload
2023-12-27 19:44:07.073 I MapDataController: Fetched 3256 elements and geometries in 3ms
2023-12-27 19:44:07.083 I MapDataController: Fetched 2956 elements and geometries in 3ms
2023-12-27 19:44:07.097 I MapDataController: Fetched 2139 elements and geometries in 2ms
2023-12-27 19:44:08.389 I MainFragment: showQuestDetails for OsmQuestKey(elementType=WAY, elementId=932888370, questTypeName=AddPisteLit)
2023-12-27 19:44:11.339 I AbstractOsmQuestForm: solve AddPisteLit for WAY 932888370, extra: false, in TagEditor: false
2023-12-27 19:44:11.343 I EditHistoryController: history: add edit AddPisteLit for [WAY 932888370]
2023-12-27 19:44:11.344 I MapDataWithEditsSource: updated: [WAY 932888370], deleted: []
2023-12-27 19:44:11.345 I OsmQuestController: Created 0 quests for 1 updated elements in 0.0s
2023-12-27 19:44:11.346 I VisibleQuestsSource: added [], deleted: [OsmQuestKey(elementType=WAY, elementId=932888370, questTypeName=AddPisteLit)]
2023-12-27 19:44:11.346 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=WAY, elementId=932888370, questTypeName=AddPisteLit)
2023-12-27 19:44:11.347 I OsmQuestController: Persisted 0 new and removed 1 already resolved quests in 0.0s
2023-12-27 19:44:11.348 I MainFragment: edited: AddPisteLit
2023-12-27 19:44:11.349 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=WAY, elementId=932888370, questTypeName=AddPisteLit)
2023-12-27 19:44:11.353 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=WAY, elementId=932888370, questTypeName=AddPisteLit)
2023-12-27 19:44:11.357 I Upload: Starting upload
2023-12-27 19:44:11.834 D ElementEditsUploader: Uploaded a UpdateElementTagsAction for [WAY 932888370]
2023-12-27 19:44:11.900 I Upload: Finished upload
2023-12-27 19:44:13.690 I MainFragment: showQuestDetails for OsmQuestKey(elementType=RELATION, elementId=10788341, questTypeName=AddPisteLit)
2023-12-27 19:44:13.786 I MapDataCache: need to fetch data in [TilesRect(left=136864, top=91292, right=136867, bottom=91295)] from database
2023-12-27 19:44:13.803 I MapDataController: Fetched 314 elements and geometries in 18ms
2023-12-27 19:44:17.397 I AbstractOsmQuestForm: solve AddPisteLit for RELATION 10788341, extra: false, in TagEditor: false
2023-12-27 19:44:17.433 I EditHistoryController: history: add edit AddPisteLit for [RELATION 10788341]
2023-12-27 19:44:17.434 I MapDataWithEditsSource: updated: [RELATION 10788341], deleted: []
2023-12-27 19:44:17.436 I OsmQuestController: Created 0 quests for 1 updated elements in 0.0s
2023-12-27 19:44:17.437 I VisibleQuestsSource: added [], deleted: [OsmQuestKey(elementType=RELATION, elementId=10788341, questTypeName=AddPisteLit)]
2023-12-27 19:44:17.437 I MainFragment: closeBottomSheet while showing OsmQuestKey(elementType=RELATION, elementId=10788341, questTypeName=AddPisteLit)
2023-12-27 19:44:17.437 I OsmQuestController: Persisted 0 new and removed 1 already resolved quests in 0.0s
2023-12-27 19:44:17.440 I MainFragment: edited: AddPisteLit
2023-12-27 19:44:17.453 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:44:17.456 I MainFragment: closeBottomSheet while showing null
2023-12-27 19:44:17.465 I Upload: Starting upload
2023-12-27 19:44:17.915 D ElementEditsUploader: Uploaded a UpdateElementTagsAction for [RELATION 10788341]
2023-12-27 19:44:17.924 E Upload: Unable to upload
java.lang.IllegalArgumentException: positions is empty
	at de.westnordost.streetcomplete.util.math.SphericalEarthMathKt.enclosingBoundingBox(SphericalEarthMath.kt:235)
	at de.westnordost.streetcomplete.data.osm.mapdata.MapDataController.updateAll(MapDataController.kt:144)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(ElementEditsUploader.kt:90)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.access$uploadEdit(ElementEditsUploader.kt:40)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invokeSuspend(ElementEditsUploader.kt:72)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invoke(ElementEditsUploader.kt:0)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invoke(ElementEditsUploader.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1.invokeSuspend(ElementEditsUploader.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


        Log warnings and errors:
        2023-12-27 19:44:17.924 E Upload: Unable to upload
java.lang.IllegalArgumentException: positions is empty
	at de.westnordost.streetcomplete.util.math.SphericalEarthMathKt.enclosingBoundingBox(SphericalEarthMath.kt:235)
	at de.westnordost.streetcomplete.data.osm.mapdata.MapDataController.updateAll(MapDataController.kt:144)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(ElementEditsUploader.kt:90)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.access$uploadEdit(ElementEditsUploader.kt:40)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invokeSuspend(ElementEditsUploader.kt:72)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invoke(ElementEditsUploader.kt:0)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$2.invoke(ElementEditsUploader.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1.invokeSuspend(ElementEditsUploader.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


<!-- 
Please provide a clear and concise description of the bug. 

Maybe it is not a bug? Check the FAQ: https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ and the SCEE readme https://github.com/Helium314/SCEE#readme

Attaching screenshots / videos:
Large images / videos can be very disturbing when reading, so please avoid attaching unnecessary screenshots and videos.
If you think they are needed, reduce the size or use thumbnails to keep the issue nicely readable.
-->

**How to Reproduce**
<!-- Add steps to reproduce this behavior here -->

**Expected Behavior**
<!-- Add a clear and concise description of what you expected to happen -->

**Does it happen in normal StreetComplete?**
<!-- If yes, then opening an issue at https://github.com/streetcomplete/StreetComplete/issues is recommended -->

**Versions affected**
<!-- Add the Android and StreetComplete version here. Please use exact version number instead of saying "latest" -->

**Comment by Helium314** [comment]
This happens when you scan for quests in an empty bbox.
It's already fixed, will be available in the next release.
